#!/usr/bin/env node
/**
 * gen-config.js — Generate config.js from .env for browser use
 * Run: node gen-config.js
 * Reads HELIUS_API_KEY from /workspace/kira/.env (or env var)
 * Writes config.js (gitignored) with the key embedded for browser consumption
 */

const fs = require('fs');
const path = require('path');

// Try to load from .env file
const envPath = path.resolve(__dirname, '../../.env');
const envVars = {};

if (fs.existsSync(envPath)) {
  const lines = fs.readFileSync(envPath, 'utf8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx < 0) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim().replace(/^['"]|['"]$/g, '');
    envVars[key] = val;
  }
}

// Prefer process.env (set by CI/CD) over .env file
const HELIUS_API_KEY = process.env.HELIUS_API_KEY || envVars.HELIUS_API_KEY || 'demo';

// Extract from SOLANA_RPC_URL as fallback (e.g., https://mainnet.helius-rpc.com/?api-key=xxx)
let apiKey = HELIUS_API_KEY;
if (apiKey === 'demo' || !apiKey) {
  const rpcUrl = process.env.SOLANA_RPC_URL || envVars.SOLANA_RPC_URL || '';
  const match = rpcUrl.match(/api-key=([^&\s]+)/);
  if (match) {
    apiKey = match[1];
    console.log('[gen-config] Extracted API key from SOLANA_RPC_URL');
  }
}

const configContent = `// config.js — AUTO-GENERATED by gen-config.js. DO NOT COMMIT.
// Run "node gen-config.js" to regenerate from .env
export const HELIUS_API_KEY = ${JSON.stringify(apiKey)};
`;

const outPath = path.resolve(__dirname, 'config.js');
fs.writeFileSync(outPath, configContent);
console.log(`[gen-config] Wrote config.js (key: ${apiKey === 'demo' ? 'demo/none' : apiKey.slice(0, 8) + '...'})`);
